name: 'Hello Perl'
description: 'Perl Github Action Template'
branding:
  icon: 'briefcase'
  color: 'blue'
inputs:
  directories:  # Change this
    description: 'Directories to look for files'
    required: true
    default: .
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - run: ${GITHUB_ACTION_PATH}/action.pl
      shell: bash
