name: Local checks
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Run over this repo
      uses: ./
      with:
        directories: ". docs"
