name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-in-container:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.36'
          - '5.38'
          - '5.40'

    name: Test perl v${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Regular tests
        run: prove -lv t/

