name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-in-container:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.32'
          - '5.34'
          - '5.30'

    name: Test perl v${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Regular tests
        env:
          PERL_VERSION: ${{ matrix.perl-version }}
        run: prove --exec 'perl -Mv${PERL_VERSION}' -lv t/

